# NPTEL R Programming – Week 5
## Python / Google Colab Complete Notebook

This notebook translates the concepts and examples from the uploaded NPTEL **Foundations of R Software – Week 5** notes into Python.

### Lectures covered
- Lecture 18: Missing Data Handling
- Lecture 19: Conditional Executions – `if` and `if-else`
- Lecture 20: Nested `if-else-if` and vectorized `ifelse`
- Lecture 21: Conditional Executions – `switch` and `which`

> **R → Python note:** R uses `NA` for missing observations. Python commonly uses `None`/`NaN`. The examples below use Python, NumPy and pandas equivalents where appropriate.

## 1. Setup

In [1]:
import numpy as np
import pandas as pd
from collections import Counter

# Lecture 18 — Missing Data Handling

The notes introduce `NA` as R's representation of a missing observation, `is.na()` for detecting missing values, `which(is.na())` for locating them, `sum(is.na())` for counting them, `complete.cases()` for identifying complete observations, and `na.omit()` for removing missing observations. fileciteturn4file0L13-L23

## Missing values: R `NA` vs Python `None` / `NaN`

For numerical work, NumPy uses `np.nan` as a common representation of a missing numeric value.

In [2]:
x = np.array([11.0, np.nan, 13.0, np.nan])
print(x)
print("Missing-value mask:", np.isnan(x))

[11. nan 13. nan]
Missing-value mask: [False  True False  True]

## Detect missing values — equivalent of `is.na()`

In [3]:
x = np.array([11.0, np.nan, 13.0, np.nan])
is_missing = np.isnan(x)

print("x:", x)
print("is.na(x) equivalent:", is_missing)

x: [11. nan 13. nan]
is.na(x) equivalent: [False  True False  True]

## Mean with missing values

The R notes show that `mean(x)` returns `NA` when the vector contains missing values, while `mean(x, na.rm = TRUE)` removes missing values before calculating the mean. fileciteturn4file0L39-L44

In [4]:
x = np.array([11.0, np.nan, 13.0, np.nan])

print("Regular NumPy mean:", np.mean(x))
print("Mean ignoring NaN (R na.rm=TRUE equivalent):", np.nanmean(x))

Regular NumPy mean: nan
Mean ignoring NaN (R na.rm=TRUE equivalent): 12.0

## NA versus NULL

The notes distinguish `NA` from `NULL`: `NA` is a placeholder for something that exists but is missing, whereas `NULL` represents something that never existed. fileciteturn4file0L55-L60

In Python, `None` is often used for the absence of an object/value. It is not identical to R's `NA`.

In [5]:
missing_value = None
numeric_missing = np.nan

print("None:", missing_value)
print("NaN:", numeric_missing)

None: None
NaN: nan

## Locate missing values — equivalent of `which(is.na(x))`

R's `which(is.na(x))` returns the positions containing `NA`. The notes demonstrate positions 2 and 4 for `c(11, NA, 13, NA)`. fileciteturn4file0L64-L71

Python uses zero-based indexing, so the corresponding zero-based positions are 1 and 3.

In [6]:
x = np.array([11.0, np.nan, 13.0, np.nan])

zero_based_positions = np.where(np.isnan(x))[0]
one_based_positions = zero_based_positions + 1

print("Python positions (0-based):", zero_based_positions)
print("R-style positions (1-based):", one_based_positions)

Python positions (0-based): [1 3]
R-style positions (1-based): [2 4]

## Count missing values — equivalent of `sum(is.na(x))`

In [7]:
x = np.array([11.0, np.nan, 13.0, np.nan])

print("Number of missing values:", np.isnan(x).sum())

Number of missing values: 2

## Complete cases — equivalent of `complete.cases()`

For a one-dimensional numeric array, a complete case is a value that is not missing.

In [8]:
x = np.array([11.0, np.nan, 13.0, np.nan])

complete = ~np.isnan(x)
print("Complete-case mask:", complete)

Complete-case mask: [ True False  True False]

## Remove missing values — equivalent of `na.omit()`

For numeric NumPy arrays, `x[~np.isnan(x)]` keeps only non-missing values.

In [9]:
x = np.array([11.0, np.nan, 13.0, np.nan])
y = x[~np.isnan(x)]

print("Original:", x)
print("After removing missing values:", y)
print("Mean after removal:", np.mean(y))

Original: [11. nan 13. nan]
After removing missing values: [11. 13.]
Mean after removal: 12.0

## Missing values in a pandas DataFrame

For tabular data, pandas provides `isna()`, `notna()`, `dropna()` and related operations.

In [10]:
df = pd.DataFrame({
    "A": [11, np.nan, 13, np.nan],
    "B": [5, 6, np.nan, 8]
})

print("DataFrame:")
display(df)

print("Missing-value mask:")
display(df.isna())

print("Missing values per column:")
print(df.isna().sum())

print("Complete rows:")
display(df.dropna())

DataFrame:

      A    B
0  11.0  5.0
1   NaN  6.0
2  13.0  NaN
3   NaN  8.0

Missing-value mask:

       A      B
0  False  False
1   True  False
2  False   True
3   True  False

Missing values per column:
A    2
B    1
dtype: int64
Complete rows:

      A    B
0  11.0  5.0

# Lecture 19 — Conditional Execution: `if` and `if-else`

The notes introduce control structures and explain that `if` executes its block when a logical condition is `TRUE`; otherwise the block is ignored. fileciteturn4file0L145-L160

## Python `if` — basic example

R:
`if (x > 4) x * 3`

Python uses the same basic conditional idea with indentation.

In [11]:
x = 5

if x > 4:
    print(x * 3)

15

## `if` with a false condition

The R example with `x = 3` produces no output because the condition `x > 4` is false. fileciteturn4file0L177-L185

In [12]:
x = 3

if x > 4:
    print(x * 3)

print("The if block was skipped because x > 4 is False.")

The if block was skipped because x > 4 is False.

## Printing based on a condition

In [13]:
x = 6

if x > 3:
    print("The value is more than 3")

The value is more than 3

## `if-else`

R's `if (...) { ... } else { ... }` maps directly to Python's `if ... else ...`. The notes use examples where `x == 3` causes `x = x - 1`, otherwise `x = 2*x`. fileciteturn4file0L223-L256

In [14]:
x = 5

if x == 3:
    x = x - 1
else:
    x = 2 * x

print(x)

10

### Same example with `x = 3`

In [15]:
x = 3

if x == 3:
    x = x - 1
else:
    x = 2 * x

print(x)

2

## `if-else` for a message

In [16]:
x = 2

if x > 3:
    print("The value is more than 3")
else:
    print("The value is less than 3")

The value is less than 3

## Logical operators

The notes mention `&&` and `||` for compound scalar conditions in R. Python uses:
- `and` for scalar logical AND
- `or` for scalar logical OR
- `not` for logical negation

In [17]:
x = 6

if x > 3 and x < 10:
    print("x is between 3 and 10")

x is between 3 and 10

# Lecture 20 — Nested `if-else-if` and `ifelse`

The notes explain that `if ... else if ... else` handles more than two alternatives. fileciteturn4file0L346-L364

## Nested / chained conditional

In [18]:
x = 5

if x == 3:
    x = x - 1
elif x < 3:
    x = x + 5
else:
    x = 2 * x

print(x)

10

### Example with `x = 2`

In [19]:
x = 2

if x == 3:
    x = x - 1
elif x < 3:
    x = x + 5
else:
    x = 2 * x

print(x)

7

### Example with `x = 3`

In [20]:
x = 3

if x == 3:
    x = x - 1
elif x < 3:
    x = x + 5
else:
    x = 2 * x

print(x)

2

## Vectorized `ifelse` — NumPy `where`

R's `ifelse(test, yes, no)` performs element-wise conditional evaluation. The notes show `ifelse(x < 6, x^2, x+1)` for `x = 1:10`. fileciteturn4file0L423-L449

In [21]:
x = np.arange(1, 11)

result = np.where(x < 6, x**2, x + 1)

print("x:", x)
print("Result:", result)

x: [ 1  2  3  4  5  6  7  8  9 10]
Result: [ 1  4  9 16 25  7  8  9 10 11]

## Vectorized even/odd classification

The notes use `ifelse(x %% 2 == 0, "even number", "odd number")`. In Python/NumPy, `%` is the modulo operator and `np.where` provides the vectorized conditional equivalent. fileciteturn4file0L456-L468

In [22]:
x = np.array([7, 9, 8, 4])

result = np.where(x % 2 == 0, "even number", "odd number")

print(result)

['odd number' 'odd number' 'even number' 'even number']

## Python list-comprehension alternative for `ifelse`

In [23]:
x = [7, 9, 8, 4]

result = ["even number" if value % 2 == 0 else "odd number" for value in x]

print(result)

['odd number', 'odd number', 'even number', 'even number']

# Lecture 21 — `switch` and `which`

The notes describe `switch()` as a multiway branch statement that tests a variable against several cases. They also introduce `which()` as a function that returns positions where a logical vector is `TRUE`. fileciteturn4file0L496-L515

## R `switch()` with integer cases

The notes show:
- `switch(2, "apple", "banana", "orange")` → `"banana"`
- `switch(1, "apple", "banana", "orange")` → `"apple"` fileciteturn4file0L551-L557

Python has no exact built-in equivalent, so a dictionary lookup is a clear translation.

In [24]:
cases = {
    1: "apple",
    2: "banana",
    3: "orange"
}

expr = 2
print(cases.get(expr))

banana

## String-based `switch()` equivalent

The R notes also show named cases such as `"colour" = "blue"` and `"volume" = 50`. fileciteturn4file0L561-L572

In [25]:
cases = {
    "colour": "blue",
    "gender": "male",
    "volume": 50
}

expr = "volume"
print(cases.get(expr))

50

## Handling a default case

R's `switch()` can return an unnamed/default value when there is no match. In Python, `dict.get(key, default)` provides a similar pattern.

In [26]:
cases = {
    "colour": "blue",
    "gender": "male",
    "volume": 50
}

expr = "size"
print(cases.get(expr, "No match"))

No match

## `which()` — find positions where a condition is true

The notes use `x = c(10,15,8,14,6,12)` and demonstrate `which(x == 14)`, `which(x != 12)` and `which(x > 10)`. fileciteturn4file0L588-L612

In [27]:
x = np.array([10, 15, 8, 14, 6, 12])

def which(condition):
    return np.where(condition)[0] + 1  # R-style 1-based positions

print("x:", x)
print("which(x == 14):", which(x == 14))
print("which(x != 12):", which(x != 12))
print("which(x > 10):", which(x > 10))

x: [10 15  8 14  6 12]
which(x == 14): [4]
which(x != 12): [1 2 3 4 5]
which(x > 10): [2 4 6]

## `which.min()` and `which.max()`

The notes demonstrate `which.min(x)` and `which.max(x)` on a 3×3 matrix. Python's `np.argmin()` and `np.argmax()` return zero-based flat indices, so `+1` gives an R-style flat position. fileciteturn4file0L616-L627

In [28]:
x = np.arange(1, 10).reshape(3, 3, order="F")

print("Matrix:")
print(x)

min_position_r = np.argmin(x) + 1
max_position_r = np.argmax(x) + 1

print("R-style which.min position:", min_position_r)
print("R-style which.max position:", max_position_r)

Matrix:
[[1 4 7]
 [2 5 8]
 [3 6 9]]
R-style which.min position: 1
R-style which.max position: 9

## `which()` on a matrix

The R notes use `which(x %% 2 == 1, arr.ind = TRUE)` to obtain row/column positions of odd values. fileciteturn4file0L632-L650

In [29]:
x = np.arange(1, 10).reshape(3, 3, order="F")

print("Matrix:")
print(x)

odd_positions = np.argwhere(x % 2 == 1)

print("Python row/column positions (0-based):")
print(odd_positions)

print("R-style row/column positions (1-based):")
print(odd_positions + 1)

Matrix:
[[1 4 7]
 [2 5 8]
 [3 6 9]]
Python row/column positions (0-based):
[[0 0]
 [0 2]
 [1 1]
 [2 0]
 [2 2]]
R-style row/column positions (1-based):
[[1 1]
 [1 3]
 [2 2]
 [3 1]
 [3 3]]

# Practice Exercises

Try these after running the examples.

### Exercise 1 — Missing data
Create an array `[10, NaN, 20, 30, NaN]` and:
1. Detect missing values.
2. Count them.
3. Find their R-style positions.
4. Calculate the mean while ignoring missing values.

### Exercise 2 — `if-else`
Write a program that prints:
- `"positive"` if a number is greater than 0
- `"negative"` if it is less than 0
- `"zero"` otherwise.

### Exercise 3 — `ifelse`
For the array `[1,2,3,4,5,6]`, return `"even"` or `"odd"` for each value.

### Exercise 4 — `switch`
Create a dictionary-based switch for menu choices:
1 → `"Apple"`, 2 → `"Banana"`, 3 → `"Orange"`.

### Exercise 5 — `which`
For `x = [5, 12, 7, 20, 3, 15]`, find the R-style positions where `x > 10`.

In [30]:
# Exercise 1 solution
x = np.array([10.0, np.nan, 20.0, 30.0, np.nan])

print("Missing mask:", np.isnan(x))
print("Count:", np.isnan(x).sum())
print("R-style positions:", np.where(np.isnan(x))[0] + 1)
print("Mean ignoring missing values:", np.nanmean(x))

Missing mask: [False  True False False  True]
Count: 2
R-style positions: [2 5]
Mean ignoring missing values: 20.0

In [31]:
# Exercise 2 solution
x = -7

if x > 0:
    print("positive")
elif x < 0:
    print("negative")
else:
    print("zero")

negative

In [32]:
# Exercise 3 solution
x = np.array([1, 2, 3, 4, 5, 6])
print(np.where(x % 2 == 0, "even", "odd"))

['odd' 'even' 'odd' 'even' 'odd' 'even']

In [33]:
# Exercise 4 solution
menu = {1: "Apple", 2: "Banana", 3: "Orange"}
choice = 2
print(menu.get(choice, "Invalid choice"))

Banana

In [34]:
# Exercise 5 solution
x = np.array([5, 12, 7, 20, 3, 15])
print("R-style positions:", np.where(x > 10)[0] + 1)

R-style positions: [2 4 6]

# R → Python Quick Reference

| R concept | Python / NumPy / pandas equivalent |
|---|---|
| `NA` | `np.nan` for numeric missing values |
| `is.na(x)` | `np.isnan(x)` / `pd.isna(x)` |
| `which(is.na(x))` | `np.where(np.isnan(x))[0] + 1` for R-style positions |
| `sum(is.na(x))` | `np.isnan(x).sum()` |
| `complete.cases(x)` | `~np.isnan(x)` for numeric vectors |
| `na.omit(x)` | `x[~np.isnan(x)]` |
| `if (...)` | `if ...:` |
| `if (...) else` | `if ... else ...` |
| `else if` | `elif` |
| `ifelse()` | `np.where()` |
| `switch()` | dictionary lookup / `match-case` |
| `which()` | `np.where()` |
| `which.min()` | `np.argmin()` |
| `which.max()` | `np.argmax()` |
| R indexing | 1-based |
| Python indexing | 0-based |

## End of Week 5